env:
  es6: true
  node: true
extends:
  - eslint:recommended
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: 2020
plugins:
  - prettier
root: true
rules:
  prettier/prettier: warn
overrides:
  - files:
      - '*.js'
    extends:
      - plugin:node/recommended
    plugins:
      - node
    rules:
      node/no-unpublished-require: 'off'
      node/no-unpublished-import: 'off'