env:
  es6: true
  node: true
extends:
  - eslint:recommended
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: 2020
  sourceType: module
plugins:
  - prettier
root: true
rules:
  prettier/prettier: warn
overrides:
  - files:
      - '*.js'
      - '*.mjs'
      - '*.cjs'
    extends:
      - plugin:node/recommended
    plugins:
      - node
    rules:
      node/no-unpublished-require: 'off'
      node/no-unpublished-import: 'off'
      node/no-missing-import: 'error'
      no-unused-vars: "warn"