name: prod
on:
  push:
    branches:
      - main
env:
  GCP_PROJECT: ${{ secrets.GCP_PROJ_ID }}
  GCP_REGION: asia-northeast1
  RUN_APP: hackday
  IMAGE_NAME: gcr.io/hackday/hackday-api
jobs:
  build:
    name: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Chechout
        uses: actions/checkout@v2
      - name: install
        run: yarn install
      - name: Check
        run: yarn check
      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GCP_SA_SECRET_PROD }}
          project_id: ${{ secrets.GCP_PROJ_ID }}
          service_account_email: ${{ secrets.GCP_SA_EMAIL_PROD }}
          export_default_credentials: true
      - name: Configure docker
        run: gcloud auth configure-docker --quiet
      - name: docker build
        run: |
          docker build -t ${IMAGE_NAME}:latest .
      - name: docker push
        run: |
          docker push ${IMAGE_NAME}
      - name: Deploy
        run: |-
          gcloud run deploy ${RUN_APP} \
            --quiet \
            --region $GCP_REGION \
            --project $GCP_PROJECT \
            --image ${IMAGE_NAME}:${{ github.sha }} \
            --platform managed \